[package]
name = "bottom"
version = "0.2.0"
authors = ["Clement Tsang <cjhtsang@uwaterloo.ca>"]
edition = "2018"
repository = "https://github.com/ClementTsang/bottom"
keywords = ["cli", "monitoring-tool", "top", "bottom", "graphical"]
license = "MIT"
categories = ["command-line-utilities"]
description = "A graphical top clone, written in Rust. Inspired by both gtop and gotop."
readme = "README.md"

[[bin]]
name = "btm"
path = "src/main.rs"

[profile.release]
debug = 1
# debug = true
opt-level = 'z'  # Optimize for size.
lto = true

[dependencies]
chrono = "0.4.10"
clap = "2.33.0"
fern = "0.5.9"
futures-timer = "3.0.1"
futures = "0.3.4"
heim = "0.0.9"
log = "0.4.8"
regex = "1.3.4"
sysinfo = "0.11"
tokio = "0.2.11"
winapi = "0.3.8"
crossterm = "0.14"
tui = {version = "0.8", features = ["crossterm"], default-features = false }
lazy_static = "1.4.0"
backtrace = "0.3"
toml = "0.5.6"
serde = "1.0"

[dev-dependencies]
assert_cmd = "0.12"
predicates = "1"
