[package]
name = "bottom"
version = "0.1.2"
authors = ["Clement Tsang <cjhtsang@uwaterloo.ca>"]
edition = "2018"
repository = "https://github.com/ClementTsang/bottom"
keywords = ["cli", "monitoring-tool", "top", "bottom", "graphical"]
license = "MIT"
categories = ["command-line-utilities"]
description = "A graphical top clone, written in Rust. Inspired by both gtop and gotop."
readme = "README.md"

[[bin]]
name = "btm"
path = "src/main.rs"

[profile.release]
debug = 1
opt-level = 'z'  # Optimize for size.
lto = true

[dependencies]
chrono = "0.4.10"
clap = "2.33.0"
crossterm = "0.14"
failure = "0.1.6"
fern = "0.5.9"
futures-timer = "2.0.2"
futures = "0.3.1"
heim = "0.0.9"
log = "0.4.8"
regex = "1.3.4"
sysinfo = "0.9.6" #0.9 seems to be the last working version for my Ryzen PC...
tokio = "0.2.11"
winapi = "0.3.8"
tui = {version = "0.8", features = ["crossterm"], default-features = false }
lazy_static = "1.4.0"
backtrace = "0.3"
yaml-rust = "0.4.3"

[dev-dependencies]
assert_cmd = "0.12"
predicates = "1"
