edition = "2018"
max_width = 100
newline_style = "Unix"
reorder_imports = true
fn_args_layout = "Compressed"
empty_item_single_line = false
hard_tabs = true
merge_imports = true
merge_derives = true
reorder_modules = true
reorder_impl_items = true
tab_spaces = 4
format_strings = true
