[flags]
avg_cpu = true

# Temperature is one of:
temperature_type = "c"

rate = 1000
left_legend = false
current_usage = false
group_processes = false
case_sensitive = false
whole_word = false
regex = true
