name: Packaging
description: For issues, questions, or requests regarding packaging or distribution.
labels: ["packaging"]
body:
  - type: markdown
    attributes:
      value: >
        If this is an issue about supporting a new package/installation method for a platform you use, please
        consider maintaining it yourself/with others and submitting a PR or issue with a link to it - they'll be
        very much appreciated and likely accepted very quickly. [The documentation on packaging/distribution](https://clementtsang.github.io/bottom/nightly/contribution/packaging-and-distribution/)
        may be helpful. If there are some issues with bottom itself causing problems with packaging, feel free to open
        an issue.


        If this is an issue regarding an existing distribution channel, then please understand that outside of:

          * [crates.io](https://crates.io/crates/bottom)
          * [Chocolatey](https://community.chocolatey.org/packages/bottom)
          * [Binary releases released on GitHub](https://github.com/ClementTsang/bottom/releases)


        I do _not_ personally maintain any other distribution channel. Preferably, for any issues with other distribution
        channels, you should try to first contact the package maintainers where appropriate for help regarding
        distribution-related issues (e.g. package has issues installing, is outdated, etc.) before reaching out here.


        While I am happy to help where possible, I do not personally use many of the various ways people distribute
        bottom, and as such, it's likely that I cannot help you with packaging on things I don't maintain myself beyond
        maybe pointing you towards someone to ask, and issues where I cannot help will likely be closed.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Checklist
      options:
        - label: >
            I have read and understood the above text.
          required: true

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Describe the issue
      description: >
        What is the packaging-related issue? Please be clear and concise.
      placeholder: |
        Example: Would it be possible to add shell completion generation as a separate build artifact?
